version: '3.8'

services:
  # PostgreSQL Database
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: rythm
      POSTGRES_USER: rythm_api
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./packages/db/migrations:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U rythm_api -d rythm"]
      interval: 30s
      timeout: 10s
      retries: 3

  # API Server (Production)
  api:
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    environment:
      - NODE_ENV=production
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=rythm
      - DB_USER=rythm_api
      - DB_PASSWORD=password
      - JWT_SECRET=your-production-secret-key-change-this
      - PORT=3001
      - CORS_ORIGIN=http://localhost:3000,http://localhost:3002
    ports:
      - "3001:3001"
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Mobile PWA (Production)
  mobile:
    build:
      context: .
      dockerfile: ./apps/mobile/Dockerfile
    environment:
      - NODE_ENV=production
      - API_URL=http://api:3001
      - NEXT_PUBLIC_API_URL=http://localhost:3001
    ports:
      - "3000:3000"
    depends_on:
      api:
        condition: service_healthy

volumes:
  postgres_data:

networks:
  default:
    name: rythm-network